### ISSUE TITLE
can't run python manage.py migrate

### ISSUE THREAD

**Issue by snwokenk** [tarsil/django-messages-drf#1]
I get this error when running migrate command:
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'django_messages_drf.Thread'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/3.1/topics/migrations/#dependencies for more

**Comment by dragon-lex** [comment]
I had same problem.
I just found in initial migration that base for Thread was **messages_drf.auditmodel** instead of **django_messages_drf.auditmodel**.
I renamed existed initial migration (as backup), create new one and run it. It's worked for me.

**Comment by tarsil** [comment]
@snwokenk @dragon-lex apologies as I had an issue before and I couldn't see this before. I'm aware of this bug and it was based on a rename previously done. @dragon-lex thank you for your comment. If you want feel free to open a PR there and I can merge or during this week I can change it. Again, apologies.

**Comment by dragon-lex** [comment]
@tarsil Well it's good to prepare repo to push changed files and make PRs.
I will create PR then.

BTW, as I see it, tests may also have same naming problem.

**Comment by tarsil** [comment]
@dragon-lex well spotted, when I did the first version it was fine but for some reason the merging didn't work as expected. I will also change that and activate the CI, it will be easier

**Comment by tarsil** [comment]
@dragon-lex @snwokenk the issue has been fixed. Also, I've updated the circle ci to make sure it passes everything. The version **1.0.2** has been released. Thank you for your contribution 👍
