### ISSUE TITLE
Accessing POST request (reply in a thread) of ThreadCRUDApiView without a user_id in the parameter.

### ISSUE THREAD

**Issue by cloudlessdreams** [tarsil/django-messages-drf#11]
Love this Django-messages-DRF packaged just having a slight issue.

I'm trying to reply to the thread without passing a **user_id** as suggested in the comment but the URL for this view has a user_id as a keyword argument. 

`path('message/thread/<uuid>/<user_id>/send/', views.ThreadCRUDApiView.as_view(), name='thread-send'),`

```
ThreadCRUDApiView(DjangoMessageDRFAuthMixin, ThreadMixin, RequireUserContextView, APIView):
    """
    View that allows the reply of a specific message as well as the
    We will apply some pagination to return a list for the results and therefore

    1. This API gets or creates the Thread~
    2. If a UUID is passed, then a Thread is validated and created but if only a user_id is
    passed, then it will create a new thread and start a conversation.
    """

    serializer_class = THREAD_REPLY_SERIALIZER

    def post(self, request, uuid=None, *args, **kwargs):
        """
        Replies a mensage in given thread
        """
        thread = self.get_thread() if uuid else None
        user = self.get_user()

        if not user:
            raise NotFound()

        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        subject = serializer.data.get('subject') or thread.subject
        if not thread:
            msg = Message.new_message(
                from_user=self.request.user, to_users=[user], subject=subject,
                content=serializer.data.get('message')
            )

        else:
            msg = Message.new_reply(thread, self.request.user, serializer.data.get('message'))
            thread.subject = subject
            thread.save()

        message = MessageSerializer(msg, context=self.get_serializer_context())
        return Response(message.data, status=status.HTTP_200_OK)
```

So to summarise to reply with a message in the thread; can you do it without passing a user_id as a parameter; if yes how? and if no can you elaborate or explain what you meant by your comment?!

Many thanks!

**Comment by tarsil** [comment]
@cloudlessdreams first thank you for using the package, means a lot. 

1. No, it not possible without the user ID because what we do is to basically match the UUID against a user id to validate if the user really belongs to it and avoid the message being sent to the wrong person by mistake or any middle man issue.

You can always do your own view and you just need to remove the user = get_user() that is inherited from the ThreadMixin, hence also the id.

I hope it helps and the package is useful to you.

The comments actually need updating, these are the old version but now it's different. You can see in the code where we use the user and the thread, both coming from the mixin. 

Nice catch, will update this week!

**Comment by cloudlessdreams** [comment]
Thanks for clarifying. I have a forked version with some customisation but this saved me hours of work.

I actually understand the logic and m2m through models quite deeply as I have an entire dB with custom through models.

I don't if being a native English speaker helps but I can definitely go through it, rewrite some of the comments and proof read the notes if that helps?

Let me know.

Thanks again!

**Comment by cloudlessdreams** [comment]
Also how can I add multiple user_ids to the `to_users` looks like I have to create a custom view or modify to handle this?

**Comment by tarsil** [comment]
@cloudlessdreams so,

1. From your second comment - Sure, have a look.
2. Message.new_message() the to_users is already prepared to be a list, so yes. In this view is for an individual thread and thought to be like it. 99.9% of the cases are like this I'm afraid, the only thing you need to modify is `[user]` to `to_users=[YOUR LIST]`

**Comment by cloudlessdreams** [comment]
Thanks. Much appreciated.
