### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'providing_args'

### ISSUE THREAD

**Issue by hsb-tonmoy** [tarsil/django-messages-drf#12]
Django 4.0 has completely removed the use of **providing_args** argument to **django.dispatch.Signal**. As a result, anyone running Django 4.0 and above will see the following error when trying to migrate the initial migration:
 
```
File "....\django_messages_drf\signals.py", line 3, in <module>
    message_sent = Signal(providing_args=["message", "thread", "reply"])
TypeError: __init__() got an unexpected keyword argument 'providing_args'
```

I'm submitting a pull request to fix this problem by simply getting rid of _providing_args_

**Comment by snwokenk** [comment]
is this going to be solved anytime soon?

**Comment by tarsil** [comment]
I'm currently testing. Apologies for taking some time but I've been stuck with a lot of work. Today I will release a new version.

**Comment by tarsil** [comment]
@snwokenk Something else needed to be also changed and updated but I appreciate your time and suggestion on this and a new version was now released. 1.0.6

Thank you for you nice catch 👍🏼
