### ISSUE TITLE
I can not see my threads until receiver answer it

### ISSUE THREAD

**Issue by Sinanaltundag** [tarsil/django-messages-drf#15]
I can not get sended thread by me at inbox, if other client answer my thread I can see at my inbox

**Comment by tarsil** [comment]
as intended. Gmail and any inbox works in that way

**Comment by Sinanaltundag** [comment]
thanks for your answer, can you help me how I get my posted threads. I could not find any endpoint

**Comment by tarsil** [comment]
Wouldn't make sense having a sent view? Because having sent messages in the inbox would be confusing perhaps?

**Comment by Sinanaltundag** [comment]
you are right, I understand. I try to add sent view manually. thanks for this good package what I need

**Comment by tarsil** [comment]
@Sinanaltundag any time, feel free to ask whatever you need.
