### ISSUE TITLE
warning while running the django server in terminal

### ISSUE THREAD

**Issue by skkohli** [tarsil/django-messages-drf#16]
After installing the app,on terminal i get the warning
**"WARNINGS:
?: (2_0.W001) Your URL pattern '^messages-drf/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
"**
can you please look at this issue and tell us how to fix it. 
I am using 
Django=3.2.14 ,djangorestframework=3.13.1
thanks

**Comment by tarsil** [comment]
This is a warning, not an error @skkohli . Are you having issues?

**Comment by skkohli** [comment]
i changed path to re_path while adding urls in my app and warning disappeared. 
    **re_path(r"^messages-drf/", include("django_messages_drf.urls", namespace="django_messages_drf")),**

**Comment by tarsil** [comment]
@skkohli you are correct! This came from the previous migration. The docs were misleading. I will update them now. It is with re_path. You can also open a PR if you want to contribute? 😄 

Let me know what you prefer. I can do it myself if you want

**Comment by tarsil** [comment]
@skkohli actually I will do it because I can update the docs to use the `path`. TO do that you only need to remove the `^`. So something like this:

```python
urlpatterns = [
    # other urls
    path("messages-drf/", include("django_messages_drf.urls", namespace="django_messages_drf")),
]
```

**Comment by tarsil** [comment]
@skkohli this is now fixed. Thank you for your input!

**Comment by skkohli** [comment]
> @skkohli you are correct! This came from the previous migration. The docs were misleading. I will update them now. It is with re_path. You can also open a PR if you want to contribute? smile
> 
> Let me know what you prefer. I can do it myself if you want

sure..plz let me know ..

**Comment by tarsil** [comment]
@skkohli it's now updated
