### ISSUE TITLE
why are all the old versions yanked?

### ISSUE THREAD

**Issue by kamikaz1k** [tarsil/django-messages-drf#18]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/11997716/224523814-9d094cfe-30cc-47dc-b8f2-3baf4dba5264.png">

**Comment by tarsil** [comment]
Oh this was a mistake by the time I released the last version. I will try to revert the process.

**Comment by kamikaz1k** [comment]
Oh okay, no problem. It is still possible to download so nobody is blocked. But it is scary to see. And there’s no reason given.

thanks for replying.

And hope all is well with you!

**Comment by tarsil** [comment]
Yap, it is fixed now :). Nothing to worry about :). 

I'm good @kamikaz1k thank you for asking. Been very busy with 3 specific products and iterating on them as they are production ready and being used by a lot of people.

* Esmerald - https://www.github.com/dymmond/esmerald & https://esmerald.dev (docs) - I'm sure you will love this one

* Saffier - https://www.github.com/tarsil/saffier & https://saffier.tarsild.io (docs) - ORM with the same Django feel interface but built on the top of SQLAlchemy core. This one was a pleasure to design. 

* Asyncz - https://www.github.com/tarsil/asyncz & https://asyncz.tarsild.io (docs) - Async scheduler. Basically what if APScheduler was in pydantic and with the latest flavours

I hope you are well as well
