### ISSUE TITLE
[request] fall back to username when serializing sender.display_name field

### ISSUE THREAD

**Issue by kamikaz1k** [tarsil/django-messages-drf#4]
hi o/ - thanks for writing this library

I am just starting to use this library (was very happy for 1.0.2 release), and hope I can leverage it for my application.

in my app, we use a custom model with a `fullname` field, since first/last name does not always work for us. We also allow the user to fully exclude their name, and just rely on `username`. What do you think about extending the library to allow overriding which field to use when determining what to serialize for the `sender.display_name` field? Or at the very least, fall back to `username` if the return is `' '` (which is my case)?

The fail back change should be a small patch to `SenderReceiverSerializer` [here](https://github.com/tarsil/django-messages-drf/blob/444dd0339c4718eafec3b3cdcca3a49118940940/django_messages_drf/serializers.py#L25). But perhaps you want something more robust.

Either way, I think having the field name being configurable is a useful feature.

Thanks again!

**Comment by tarsil** [comment]
@kamikaz1k thank you very much for your words as that gives me motivation to keep doing it better. 

I like your idea actually and this was actually for the normal Django first and last name but nothing like providing some settings to allow the overrides.

Could you share some examples of what you want to achieve? I might be able to understand better and maybe actually make it more generic for everyone and release a 1.0.3?

I'm glad you are really enjoying the package and I hope it helps you

**Comment by kamikaz1k** [comment]
@tarsil Sure thing!

In my specific case, I am using the following structure:

```python
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

class UserProfile(models.Model):
    """model to represent additional information about users"""
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    fullname = models.CharField(max_length=250, blank=True)

    ... other fields ...
```

You could also use a totally custom `User` model like in the [docs.](https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#specifying-a-custom-user-model)


But again, for my specific case, I do not use the `first_name` and `last_name` fields. Instead I prefer to use `user.profile.fullname`. However, the `fullname` field is optional for my application. Most users will only have a `username`. Which means, currently, the `Thread.sender.display_name` for a user without a name, is going to be `' '` (since `first_name` and `last_name` are `''`).

What I would like, is to be able to serialize a different value for this field. In my use case specifically, I wanna try `user.profile.fullname` and if that's blank, I want to fallback to `user.username`.

But that's specific to me. A more general approach I have seen (as with the [`dj_rest_auth`](https://dj-rest-auth.readthedocs.io/en/latest/faq.html?highlight=USER_DETAILS_SERIALIZER#faq) via `USER_DETAILS_SERIALIZER`) is providing a override in `settings.py`. That way you can provide a way to customize the serializer used to generate the `sender` in generic way. More visually, example in `settings.py` you can set:

```python
# settings.py
...
MESSAGES_DRF_SERIALIZERS = {
    'SENDER_DETAILS_SERIALIZER': 'app.serializers.SenderSerializer'
}
```

What do you think?

**Comment by tarsil** [comment]
@kamikaz1k To be fair your examples are good but the best approach would be to simply provide a setting like you mentioned where I just pass it and you can override it with your serializer. I use the settings.AUTH_USER default from Django because you can use like your example of a model (the way they actually recommend) or inheriting from the abstract user but it's irrelevant. 

Using the setting where you can pass your own serializer would be better because if you don't pass the setting then default the current one.

Make sense like this?

Is the rest of the plugin useful at least? I use it a lot in my projects and that's why I decided to make it public :-)

**Comment by kamikaz1k** [comment]
Yes, I think the approach to provide a CustomSerializer in `settings.py` makes sense. Let me know if I can help!

As for the plugin overall, yes it is quite useful! I was able to get my feature rolling very quickly, you have made some thoughtful decisions. Though I have only started using it (product is still in development), so I am still exploring. I have some suggestions for documentation that I was intending to put up PRs for later. I have a demo with my client relatively soon, so I am trying to have something polished ready for them.

If I were to offer some feature suggestions (something I will need to build myself eventually I think), I can think of a few things:
1. Ability to block users
2. Editing a sent message
3. Using `ViewSet` for the view classes so the api self documents (I am relatively new to Django, I used to do a lot of flask, and DRF ViewSet powered API discovery is very cool)
4. Group (multiple users) thread

**Comment by tarsil** [comment]
@kamikaz1k I'm glad I could help and very happy that helped you with your project.

So, first things first because I'm also working full time and my time and dedication is quite limited for that reason but I can already cyekk you this.

- Documentation is already should be available his weekend or next week.
- Some new features are already being thought that match also what you mentioned, including the edit of a message.

I think that making too specific will remove the availability of people to make it "theirs" but there are some considerations already.


Stay tuned and keep up the good work.

**Comment by tarsil** [comment]
I'm closing this issue as the new version allows overrides of the serializers via `settings`.

More info [here](https://tarsil.github.io/django-messages-drf/settings/)

**Comment by tarsil** [comment]
@kamikaz1k let me know what do you think 😄 I think this solves a lot of the issues and the docs also help. I tried to put as much description as possible without going into much detail as wasn't needed.

**Comment by kamikaz1k** [comment]
Hey @tarsil I finally had the chance to check it out. The `DJANGO_MESSAGES_DRF_INBOX_SERIALIZER` worked perfectly, thanks! I think your library users would still find value in just customizing the `SenderReceiverSerializer`, but I was able to create something compact by just overriding the necessary fields of the library `InboxSerializer`.

Thanks for your hard work, and quick ship!

**Comment by tarsil** [comment]
@kamikaz1k that is really good news and I'm thinking about some new possible designs for this. I hope it was good to use to you and thank you for your contributions on this.
