### ISSUE TITLE
DJANGO_MESSAGES_DRF_MESSAGE_SERIALIZER is misleading

### ISSUE THREAD

**Issue by kamikaz1k** [tarsil/django-messages-drf#7]
It took me a while to realize that `DJANGO_MESSAGES_DRF_MESSAGE_SERIALIZER` is actually overriding `ThreadReplySerializer`. Consider renaming `DJANGO_MESSAGES_DRF_MESSAGE_SERIALIZER` to `DJANGO_MESSAGES_DRF_THREAD_REPLY_SERIALIZER`.

I also realized while looking at the docs, that there is no list of plain url paths that map back to the url names.

I would have expected to see the paths along with the names in this section: https://tarsil.github.io/django-messages-drf/overview/url-names/

something like:

| View                              | Path                    | Description                                                             |
|-----------------------------------|-------------------------|-------------------------------------------------------------------------|
| django_messages_drf:thread-create | /message/thread/1/send/ | Create new message to specific user. Requires a User PK (user to send). |

Otherwise it would be nice if the api auto-documented using the `ViewSet` discovery api

**Comment by tarsil** [comment]
@kamikaz1k yes, I was thinking the same as well actually. After some consideration, I will do that this week no worries. The docs will be also updated to be a little bit clearer. 

I hope at least this didn't block you.

**Comment by kamikaz1k** [comment]
no worries @tarsil - I was able to work around it.

But thanks for checking in :)
